// Code generated by protoc-gen-go. DO NOT EDIT.
// source: news.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	news.proto

It has these top-level messages:
	News
	PostNewsRequest
	PostNewsResponse
	GetNewsRequest
	GetNewsResponse
	GetAllNewsRequest
	GetAllNewsResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type News struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Author   string   `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	NewsType string   `protobuf:"bytes,5,opt,name=news_type,json=newsType" json:"news_type,omitempty"`
	Tags     []string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
}

func (m *News) Reset()                    { *m = News{} }
func (m *News) String() string            { return proto.CompactTextString(m) }
func (*News) ProtoMessage()               {}
func (*News) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *News) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *News) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *News) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *News) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *News) GetNewsType() string {
	if m != nil {
		return m.NewsType
	}
	return ""
}

func (m *News) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PostNewsRequest struct {
	Title    string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Author   string   `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	NewsType string   `protobuf:"bytes,5,opt,name=news_type,json=newsType" json:"news_type,omitempty"`
	Tags     []string `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
}

func (m *PostNewsRequest) Reset()                    { *m = PostNewsRequest{} }
func (m *PostNewsRequest) String() string            { return proto.CompactTextString(m) }
func (*PostNewsRequest) ProtoMessage()               {}
func (*PostNewsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostNewsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostNewsRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostNewsRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PostNewsRequest) GetNewsType() string {
	if m != nil {
		return m.NewsType
	}
	return ""
}

func (m *PostNewsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PostNewsResponse struct {
	News *News `protobuf:"bytes,1,opt,name=news" json:"news,omitempty"`
}

func (m *PostNewsResponse) Reset()                    { *m = PostNewsResponse{} }
func (m *PostNewsResponse) String() string            { return proto.CompactTextString(m) }
func (*PostNewsResponse) ProtoMessage()               {}
func (*PostNewsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PostNewsResponse) GetNews() *News {
	if m != nil {
		return m.News
	}
	return nil
}

type GetNewsRequest struct {
	NewsType string `protobuf:"bytes,1,opt,name=news_type,json=newsType" json:"news_type,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetNewsRequest) Reset()                    { *m = GetNewsRequest{} }
func (m *GetNewsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNewsRequest) ProtoMessage()               {}
func (*GetNewsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetNewsRequest) GetNewsType() string {
	if m != nil {
		return m.NewsType
	}
	return ""
}

func (m *GetNewsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetNewsResponse struct {
	News *News `protobuf:"bytes,1,opt,name=news" json:"news,omitempty"`
}

func (m *GetNewsResponse) Reset()                    { *m = GetNewsResponse{} }
func (m *GetNewsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNewsResponse) ProtoMessage()               {}
func (*GetNewsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetNewsResponse) GetNews() *News {
	if m != nil {
		return m.News
	}
	return nil
}

type GetAllNewsRequest struct {
	NewsType string `protobuf:"bytes,1,opt,name=news_type,json=newsType" json:"news_type,omitempty"`
	Skip     int32  `protobuf:"varint,2,opt,name=skip" json:"skip,omitempty"`
	Take     int32  `protobuf:"varint,3,opt,name=take" json:"take,omitempty"`
}

func (m *GetAllNewsRequest) Reset()                    { *m = GetAllNewsRequest{} }
func (m *GetAllNewsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllNewsRequest) ProtoMessage()               {}
func (*GetAllNewsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetAllNewsRequest) GetNewsType() string {
	if m != nil {
		return m.NewsType
	}
	return ""
}

func (m *GetAllNewsRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetAllNewsRequest) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetAllNewsResponse struct {
	Allnews []*News `protobuf:"bytes,1,rep,name=allnews" json:"allnews,omitempty"`
}

func (m *GetAllNewsResponse) Reset()                    { *m = GetAllNewsResponse{} }
func (m *GetAllNewsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllNewsResponse) ProtoMessage()               {}
func (*GetAllNewsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAllNewsResponse) GetAllnews() []*News {
	if m != nil {
		return m.Allnews
	}
	return nil
}

func init() {
	proto.RegisterType((*News)(nil), "pb.News")
	proto.RegisterType((*PostNewsRequest)(nil), "pb.PostNewsRequest")
	proto.RegisterType((*PostNewsResponse)(nil), "pb.PostNewsResponse")
	proto.RegisterType((*GetNewsRequest)(nil), "pb.GetNewsRequest")
	proto.RegisterType((*GetNewsResponse)(nil), "pb.GetNewsResponse")
	proto.RegisterType((*GetAllNewsRequest)(nil), "pb.GetAllNewsRequest")
	proto.RegisterType((*GetAllNewsResponse)(nil), "pb.GetAllNewsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NewsService service

type NewsServiceClient interface {
	PostNews(ctx context.Context, in *PostNewsRequest, opts ...grpc.CallOption) (*PostNewsResponse, error)
	GetNews(ctx context.Context, in *GetNewsRequest, opts ...grpc.CallOption) (*GetNewsResponse, error)
	GetAllNews(ctx context.Context, in *GetAllNewsRequest, opts ...grpc.CallOption) (*GetAllNewsResponse, error)
}

type newsServiceClient struct {
	cc *grpc.ClientConn
}

func NewNewsServiceClient(cc *grpc.ClientConn) NewsServiceClient {
	return &newsServiceClient{cc}
}

func (c *newsServiceClient) PostNews(ctx context.Context, in *PostNewsRequest, opts ...grpc.CallOption) (*PostNewsResponse, error) {
	out := new(PostNewsResponse)
	err := grpc.Invoke(ctx, "/pb.NewsService/PostNews", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GetNews(ctx context.Context, in *GetNewsRequest, opts ...grpc.CallOption) (*GetNewsResponse, error) {
	out := new(GetNewsResponse)
	err := grpc.Invoke(ctx, "/pb.NewsService/GetNews", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GetAllNews(ctx context.Context, in *GetAllNewsRequest, opts ...grpc.CallOption) (*GetAllNewsResponse, error) {
	out := new(GetAllNewsResponse)
	err := grpc.Invoke(ctx, "/pb.NewsService/GetAllNews", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NewsService service

type NewsServiceServer interface {
	PostNews(context.Context, *PostNewsRequest) (*PostNewsResponse, error)
	GetNews(context.Context, *GetNewsRequest) (*GetNewsResponse, error)
	GetAllNews(context.Context, *GetAllNewsRequest) (*GetAllNewsResponse, error)
}

func RegisterNewsServiceServer(s *grpc.Server, srv NewsServiceServer) {
	s.RegisterService(&_NewsService_serviceDesc, srv)
}

func _NewsService_PostNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).PostNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NewsService/PostNews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).PostNews(ctx, req.(*PostNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NewsService/GetNews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GetNews(ctx, req.(*GetNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GetAllNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GetAllNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NewsService/GetAllNews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GetAllNews(ctx, req.(*GetAllNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NewsService",
	HandlerType: (*NewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostNews",
			Handler:    _NewsService_PostNews_Handler,
		},
		{
			MethodName: "GetNews",
			Handler:    _NewsService_GetNews_Handler,
		},
		{
			MethodName: "GetAllNews",
			Handler:    _NewsService_GetAllNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news.proto",
}

func init() { proto.RegisterFile("news.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x93, 0xbf, 0x6e, 0xe2, 0x40,
	0x10, 0xc6, 0xcf, 0xc6, 0xe6, 0xcf, 0x20, 0xc1, 0xdd, 0xc0, 0xa1, 0x15, 0x77, 0x05, 0xda, 0x8a,
	0x8a, 0x44, 0x24, 0x52, 0xd2, 0x50, 0xa4, 0xa2, 0x8b, 0x22, 0x27, 0x45, 0xba, 0x88, 0x3f, 0xa3,
	0xc4, 0xc2, 0xb2, 0x37, 0xec, 0x12, 0xc4, 0x2b, 0xa4, 0xc9, 0x03, 0xe5, 0xe5, 0xa2, 0x1d, 0xdb,
	0x90, 0xa5, 0xa2, 0x4b, 0x37, 0xf3, 0xcd, 0x8c, 0xbf, 0xcf, 0x3f, 0xcb, 0x00, 0x29, 0x6d, 0xf5,
	0x48, 0xad, 0x33, 0x93, 0xa1, 0xaf, 0xe6, 0xf2, 0xc3, 0x83, 0xe0, 0x96, 0xb6, 0x1a, 0x5b, 0xe0,
	0xc7, 0x4b, 0xe1, 0x0d, 0xbc, 0x61, 0x23, 0xf2, 0xe3, 0x25, 0x76, 0x21, 0x34, 0xb1, 0x49, 0x48,
	0xf8, 0x2c, 0xe5, 0x0d, 0x0a, 0xa8, 0x2d, 0xb2, 0xd4, 0x50, 0x6a, 0x44, 0x85, 0xf5, 0xb2, 0xc5,
	0x1e, 0x54, 0x67, 0x1b, 0xf3, 0x92, 0xad, 0x45, 0xc0, 0x83, 0xa2, 0xc3, 0x7f, 0xd0, 0xb0, 0x96,
	0x4f, 0x66, 0xa7, 0x48, 0x84, 0x3c, 0xaa, 0x5b, 0xe1, 0x61, 0xa7, 0x08, 0x11, 0x02, 0x33, 0x7b,
	0xd6, 0xa2, 0x3a, 0xa8, 0x0c, 0x1b, 0x11, 0xd7, 0xf2, 0xdd, 0x83, 0xf6, 0x5d, 0xa6, 0x8d, 0x4d,
	0x15, 0xd1, 0xeb, 0x86, 0xb4, 0xf9, 0xb9, 0x30, 0xe7, 0xf0, 0xfb, 0x90, 0x45, 0xab, 0x2c, 0xd5,
	0x84, 0xff, 0x21, 0xb0, 0x37, 0xcc, 0xaa, 0x39, 0xae, 0x8f, 0xd4, 0x7c, 0xc4, 0x73, 0x56, 0xe5,
	0x04, 0x5a, 0x53, 0x72, 0xc2, 0x3b, 0xa6, 0xde, 0x91, 0x69, 0x8e, 0xdd, 0x2f, 0xb1, 0xcb, 0x33,
	0x68, 0xef, 0xcf, 0x4f, 0xf2, 0x7b, 0x84, 0x3f, 0x53, 0x32, 0x37, 0x49, 0x72, 0xb2, 0x25, 0x42,
	0xa0, 0x57, 0xb1, 0x62, 0xd3, 0x30, 0xe2, 0x3a, 0x7f, 0xf7, 0x15, 0x31, 0xc7, 0x30, 0xe2, 0x5a,
	0x5e, 0x03, 0x7e, 0x7f, 0x72, 0x91, 0x46, 0x42, 0x6d, 0x96, 0x24, 0x45, 0xa0, 0x8a, 0x13, 0xa8,
	0x1c, 0x8c, 0x3f, 0x3d, 0x68, 0x5a, 0xe5, 0x9e, 0xd6, 0x6f, 0xf1, 0x82, 0xf0, 0x0a, 0xea, 0x25,
	0x45, 0xec, 0xd8, 0xf5, 0xa3, 0xef, 0xdb, 0xef, 0xba, 0x62, 0x6e, 0x25, 0x7f, 0xe1, 0x25, 0xd4,
	0x0a, 0x1a, 0x88, 0x76, 0xc5, 0x25, 0xdb, 0xef, 0x38, 0xda, 0xfe, 0x6a, 0x02, 0x70, 0x08, 0x8e,
	0x7f, 0x8b, 0x25, 0x17, 0x51, 0xbf, 0x77, 0x2c, 0x97, 0xe7, 0xf3, 0x2a, 0xff, 0x1d, 0x17, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x92, 0xd5, 0x73, 0x79, 0x2b, 0x03, 0x00, 0x00,
}
